-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgWk7k0J3/bY9lYYFt
vzINVGjGQPbAV0ENox5W1n/AqLKgCgYIKoZIzj0DAQehRANCAAQ4tVj0tufLxGnt
isITptvoq/4HgjMCzOS/BjD0bh/kQ8SUuAopMROYgCwqiYOE1pPSK/86w22hHL9I
M+nFIvFB
-----END PRIVATE KEY-----